baseURL = "https://example.com/"
languageCode = "en-us"
title = "bardslog"
theme = "vintage-web-hugo-theme"

[module]
  [[module.imports]]
    path = "github.com/raisingpixels/vintage-web-hugo-theme"
