name: Daily AI Post

on:
  schedule:
    - cron: "0 12 * * *"  # Runs every day at 12:00 UTC
  workflow_dispatch:

jobs:
  generate-post:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install openai==0.28.1

      - name: Generate new post and image
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python <<'PYCODE'
          import openai, datetime, os, base64
          from textwrap import dedent

          openai.api_key = os.getenv("OPENAI_API_KEY")
          date = datetime.date.today().isoformat()
          os.makedirs("content", exist_ok=True)
          os.makedirs("static/images", exist_ok=True)

          # Generate text
          text_prompt = f"Write a 500-word reflective daily blog post about Historical European Martial Arts (HEMA) — training, technique, or philosophy."
          post = openai.ChatCompletion.create(
              model="gpt-3.5-turbo",
              messages=[{"role": "user", "content": text_prompt}]
          ).choices[0].message["content"]

          # Generate image
          img_prompt = f"Medieval fencing illustration, European swordsmanship training, illuminated manuscript style, subtle parchment tone"
          img = openai.Image.create(prompt=img_prompt, n=1, size="800x400")
          img_url = img['data'][0]['url']

          # Save image locally
          import requests
          img_data = requests.get(img_url).content
          img_path = f"static/images/{date}.jpg"
          with open(img_path, "wb") as f:
              f.write(img_data)

          # Write Markdown post
          md_path = f"content/{date}-hema-journal.md"
          with open(md_path, "w") as f:
              f.write(dedent(f"""\
              ---
              title: "HEMA Journal {date}"
              date: {date}
              image: "/images/{date}.jpg"
              ---
              
              {post}
              """))
          PYCODE

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated post for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
